In [1]:
import sys
sys.path.append('c:/users/sherman luo/appdata/local/programs/python/python36-32/lib/site-packages')
import pickle
import random
import categorize
from divegame import diveGame
import numpy as np
from fatal_flaw import getActions
import matplotlib.pyplot as plt
import divegame

import m2

import importlib
importlib.reload(categorize)
importlib.reload(divegame)
from categorize import CorrectionType, isUnderwater, targetsSurface, targetsPiece

In [10]:


mistakevalues = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
arr =np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
groups = np.array([0, 0, 0, 0, 0])

for state, move in playdata:
    arollout, urscore = map[(state, move)]
    for action in state.getLegalActions():
        if action != move:
            rollout, movescore = map[(state, action)]
            if movescore > urscore + 35:
                mType = categorize.categorize(state, move, rollout, arollout)
                
                if mType == CorrectionType.A or mType == CorrectionType.J or mType == CorrectionType.B:
                    groups[0] += 1
                if mType == CorrectionType.D or mType == CorrectionType.E or mType == CorrectionType.F:
                    groups[1] += 1
                if mType == CorrectionType.G or mType == CorrectionType.H:
                    groups[2] += 1
                if mType == CorrectionType.I or mType == CorrectionType.K:
                    groups[3] += 1
                if mType == CorrectionType.C1 or mType == CorrectionType.C2 or mType == CorrectionType.C3 or mType == CorrectionType.C4:
                    groups[4] += 1
                
                if mType == CorrectionType.A:
                    arr[0] += 1
                    mistakevalues[0] += movescore - urscore
                if mType == CorrectionType.B:
                    arr[1] += 1
                    mistakevalues[1] += movescore - urscore
                if mType == CorrectionType.D:
                    arr[2] += 1
                    mistakevalues[2] += movescore - urscore
                if mType == CorrectionType.E:
                    arr[3] += 1
                    mistakevalues[3] += movescore - urscore
                if mType == CorrectionType.F:
                    arr[4] += 1
                    mistakevalues[4] += movescore - urscore
                if mType == CorrectionType.G:
                    arr[5] += 1
                    mistakevalues[5] += movescore - urscore
                if mType == CorrectionType.H:
                    arr[6] += 1
                    mistakevalues[6] += movescore - urscore
                if mType == CorrectionType.I:
                    arr[7] += 1
                    mistakevalues[7] += movescore - urscore
                if mType == CorrectionType.J:
                    arr[8] += 1
                    mistakevalues[8] += movescore - urscore
                if mType == CorrectionType.K:
                    arr[9] += 1
                    mistakevalues[9] += movescore - urscore
                if mType == CorrectionType.C1:
                    arr[10] += 1
                    mistakevalues[10] += movescore - urscore
                if mType == CorrectionType.C2:
                    arr[11] += 1
                    mistakevalues[11] += movescore - urscore
                if mType == CorrectionType.C3:
                    arr[12] += 1
                    mistakevalues[12] += movescore - urscore
                if mType == CorrectionType.C4:
                    arr[13] += 1
                    mistakevalues[13] += movescore - urscore
                    
                    

averageMistakes = [mistakevalues[i] / arr[i] if arr[i] > 0 else 0 for i in range(len(arr)) ]          
print(arr, sum(arr))          
print(groups, sum(groups))
    
    

[1 1 2 0 0 0 0 2 0 2 0 0 2 1] 11
[2 2 0 4 3] 11


In [11]:
FFF = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
groups = np.array([0, 0, 0, 0, 0])

for i in range(1, 3):  
    #print("----------------------------------------------------------------")
    f = open("playdata/balvin" + str(i), 'rb')
    data = pickle.load(f)[1]
    
    biggestMistake = 0
    bigType = None
    sarollout = None 
    scrollout = None
    sstate = None
    
    for state, move in data:
        arollout, urscore = map[(state, move)]
        for action in state.getLegalActions():
            if action != move:
                rollout, movescore = map[(state, action)]

                if movescore > urscore:
                    mType = categorize.categorize(state, move, rollout, arollout)
                    #print(mType, movescore - urscore, "your", move, "theirs", action)
                    if movescore - urscore > biggestMistake:
                        bigType = mType
                        biggestMistake = movescore - urscore
                        sarollout = arollout
                        scrollout = rollout
                        sstate = state
    if bigType:
        if bigType == CorrectionType.A:
            FFF[0] += 1
        if bigType == CorrectionType.B:
            FFF[1] += 1
        if bigType == CorrectionType.C:
            sstate.printBoard()
            print(sarollout)
            print(scrollout)
            print(biggestMistake)
            FFF[2] += 1
        if bigType == CorrectionType.D:
            FFF[3] += 1
        if bigType == CorrectionType.E:
            FFF[4] += 1
        if bigType == CorrectionType.F:
            FFF[5] += 1
        if bigType == CorrectionType.G:
            FFF[6] += 1
        if bigType == CorrectionType.H:
            FFF[7] += 1
        if bigType == CorrectionType.I:
            FFF[8] += 1
        if bigType == CorrectionType.J:
            FFF[9] += 1
        if bigType == CorrectionType.K:
            FFF[10] += 1
        if bigType == CorrectionType.C1:
            FFF[11] += 1
        if bigType == CorrectionType.C2:
            FFF[12] += 1
        if bigType == CorrectionType.C3:
            FFF[13] += 1
        if bigType == CorrectionType.C4:
            FFF[14] += 1
            
        if bigType == CorrectionType.A or bigType == CorrectionType.J or bigType == CorrectionType.B:
            groups[0] += 1
        if bigType == CorrectionType.D or bigType == CorrectionType.E or bigType == CorrectionType.F:
            groups[1] += 1
        if bigType == CorrectionType.G or bigType == CorrectionType.H:
            groups[2] += 1
        if bigType == CorrectionType.I or bigType == CorrectionType.K:
            groups[3] += 1
        if bigType == CorrectionType.C1 or bigType == CorrectionType.C2 or bigType == CorrectionType.C3 or bigType == CorrectionType.C4:
            groups[4] += 1

        












In [12]:
print(FFF)
print(groups)

[1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 0 0]


In [ ]:
f = open("sherm 1", 'rb')
data = pickle.load(f)[1]
f = open("sherm 2", 'rb')
data += pickle.load(f)[1]
f = open("sherm 3", 'rb')
data += pickle.load(f)[1]
f = open("sherm 4", 'rb')
data += pickle.load(f)[1]
f = open("sherm 5", 'rb')
data += pickle.load(f)[1]
f = open("sherm 6", 'rb')
data += pickle.load(f)[1]
f = open("sherm 7", 'rb')
data += pickle.load(f)[1]
f = open("sherm 9", 'rb')
data += pickle.load(f)[1]
f = open("sherm 10", 'rb')
data += pickle.load(f)[1]



In [ ]:
random.shuffle(data)

In [ ]:
data = data[:40]
data = [a for a,b in data]
data = set(data)
print(len(data))
print(data)

In [ ]:
f = open("qvalues", 'wb')

In [ ]:
map = {}
for state in data:
    for action in state.getLegalActions():
        temp = state.getSuccessor(action)[0]
        states, rollout, scores, startNode = m2.getRollout(temp, 150000)
        map[(state, action)] = scores[-1]
    
pickle.dump(map, f)
f.close()

In [ ]:
pickle.dump(map, f)
f.close()

In [155]:
count = 0
arr =np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
states = [a for a, b in map.keys()]
for state, action in data:
    if state in states:
        count += 1
        for alt in state.getLegalActions():
            
            if alt != action:
                #print(not isUnderwater(state), targetsSurface(action), targetsPiece(alt))
                mType = categorize(state, action, alt)
                if mType == CorrectionType.A:
                    arr[0] += 1
                if mType == CorrectionType.B:
                    arr[1] += 1
                if mType == CorrectionType.C:
                    arr[2] += 1
                if mType == CorrectionType.D:
                    arr[3] += 1
                if mType == CorrectionType.E:
                    arr[4] += 1
                if mType == CorrectionType.F:
                    arr[5] += 1
                if mType == CorrectionType.G:
                    arr[6] += 1
                if mType == CorrectionType.H:
                    arr[7] += 1
                if mType == CorrectionType.I:
                    arr[8] += 1
                if mType == CorrectionType.J:
                    arr[9] += 1
                if mType == CorrectionType.K:
                    arr[10] += 1
                #print(mType)
print(arr)

TypeError: 'module' object is not callable

In [7]:
states = set()
for a, b in map:
    states.add(a)
len(states)

22

In [ ]:
states = list(states)

In [ ]:
f = open("testStates", 'wb')
pickle.dump(states, f)

In [ ]:
f = open("testD", "rb")
pickle.load(f)

In [2]:
f = open("playdata/balvin1", 'rb')
playdata = pickle.load(f)[1]
f = open("playdata/balvin2", 'rb')
playdata += pickle.load(f)[1]


print(len(playdata))

22


In [3]:
map = {}
for state, move in playdata:
    print("calculating...")
    actions, scores = getActions(state, 1, 100000, allRollouts = True)
    for i in range(len(actions)):
        moves = actions[i]
        score = scores[i]
        map[(state, moves[0])] = (moves, score)

calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
calculating...
